#!/bin/bash
set -euo pipefail

name=variant
OUTPUT_PATH=${OUTPUT_PATH:-"bin/${name}"}

VERSION=$( $(dirname $0)/version )

echo Building ${name} ${VERSION}

if [[ ! "${BUILD_GOOS:-}" == "" ]];then
  export GOOS=$BUILD_GOOS
fi
if [[ ! "${BUILD_GOARCH:-}" == "" ]];then
  export GOARCH=$BUILD_GOARCH
fi
PKG=$(cd $(dirname $0)/.. && pwd)
PKG=${PKG#*go/src/}
x=${PKG}/pkg/cli/version.VERSION=${VERSION}
echo Setting $x
go build -ldflags "-X $x" -a -tags netgo -installsuffix netgo -o "$OUTPUT_PATH" ./
