#!/usr/bin/env bash

set -e

name=variant

for os in linux darwin;do
    # Add architecture support here
    for arch in amd64 arm64;do
	output_folder="${os}-${arch}"
	rm -rf "$output_folder"
	mkdir "$output_folder"
	echo "Building ${name} for GOOS=${os} GOARCH=${arch}"
	OUTPUT_PATH="$output_folder/${name}" BUILD_GOOS=$os BUILD_GOARCH=$arch $(dirname $0)/build

	releaseTar="${name}-${os}-${arch}".tar.gz
	rm -rf "$releaseTar"
	set -vx
	pushd $output_folder
	tar czvf ../$releaseTar ${name}
	popd
	rm -rf "$output_folder"
	echo "${os}-${arch} --> ${releaseTar}"
    done
done
echo "Done!"
