#!/usr/bin/env bash

set -ev

if [ -z "$GITHUB_USER" ]; then
  echo GITHUB_USER must be set 1>&2
  exit 1
fi

if [ -z "$GITHUB_REPO" ]; then
  echo GITHUB_REPO must be set 1>&2
  exit 1
fi

if [ -z "$GITHUB_TOKEN" ]; then
  echo GITUB_TOKEN must be set 1>&2
  exit 1
fi

if ! which dep; then
  go get github.com/golang/dep/cmd/dep
fi

if ! which github-release; then
  go get github.com/aktau/github-release
fi

COMMIT=$(git rev-parse HEAD)
TAG=$(git describe --exact-match --abbrev=0 --tags "${COMMIT}" 2> /dev/null || true)

if [ -z "${TAG}" ]; then
  echo TAG is not set. Run git tag to tag a release 1>&2
  exit 1
fi

github-release release -t $TAG -n $TAG -c $COMMIT || true

name=variant
for os in linux darwin; do
  for arch in amd64; do
    releaseTar="${name}-${os}-${arch}".tar.gz
    github-release upload -f $releaseTar -n $releaseTar -t $TAG
  done
done

echo releases at https://github.com/mumoshu/$name/releases/tag/$TAG
